baseURL: "https://ej.saha.la"
languageCode: en-us
title: "ej.saha.la"
theme: "github.com/ejsdotsh/yacht-hugo-theme"
module:
  imports:
    - path: "github.com/ejsdotsh/yacht-hugo-theme"
      disable: false

params:
  author: "e.j. sahala (they/them)"
  copyrightFrom: "2003"
  # logoPicture: "images/ejs-sh.svg"
  profilePicture: "images/profile.png"
  profilePictureAlt: "a photo of e.j. taking a photo"

  # github integration
  gh_url: "https://api.github.com/search/repositories"
  gh_user: "ejsdotsh"

  subTitle: |
    personal site of e.j. sahala (they/them). (infrequent) musings on technology, coffee, and other stuff

  description:

# Localized dates requires Hugo version 0.87.0
localizedDates:
  true
# date format
##singleDateFormat: "2006-01-02"
##indexDateFormat: "2006-01-02"
##listDateFormat: "2006-01-02"

taxonomies:
  # year: "year"
  # month: "month"
  category: "categories"
  # series: "series"
  tag: "tags"

permalinks:
  blog: "posts/:year/:month/:slug/"
  year: "/posts/:slug/"
  month: "/posts/:slug/"

related:
  includeNewer: true
  threshold: 80
  toLower: true
  indices:
    - name: "keywords"
      weight: 100
    - name: "tags"
      weight: 80
    - name: "date"
      weight: 10.0

enableEmoji: true
enableGitInfo: true

menus:
  main:
    - identifier: "home"
      name: "home"
      weight: 100
      url: "/"
    - identifier: "about"
      name: "about"
      weight: 110
      url: "/about/"
    - identifier: "blog"
      name: "blog"
      weight: 130
      url: "https://ejs.wtf/blog/"
    - identifier: "project"
      name: "projects"
      weight: 140
      url: "/projects/"
    # - identifier: "contact"
    #   name: "contact"
    #   weight: 1000
    #   url: "/contact/"

highlight:
  style: "catppuccin-frappe"
  lineNos: true
goldmark:
  renderer:
    unsafe: true

# charts
# mermaid: true
#
# LaTeX
# katex: true
#
# params.math:
# enable: true
# use: "katex"

enableRobotsTXT: true
# minify: true
